[solution]
name = "deep-solution-v1-gdn-decode"       # Solution name
definition = "gdn_decode_qk4_v8_d128_k_last"             # Exact definition name from dataset
author = "deep"              # Team/author name

[build]
language = "cuda"               # triton | cuda
entry_point = "kernel_cuda_v4"   # Exported CUDA symbol in solution/cuda/kernel.cu
